"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Search, Eye } from "lucide-react";
import { PageHeader } from "@/components/common/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { getReports } from "@/lib/api/reports";
import { VerificationReportData } from "@/lib/types/report";

export default function ReportsPage() {
  const router = useRouter();
  const [reports, setReports] = useState<VerificationReportData[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");

  useEffect(() => {
    async function load() {
      setIsLoading(true);
      try {
        const data = await getReports();
        setReports(data);
      } catch (err) {
        console.error("Error loading reports", err);
      } finally {
        setIsLoading(false);
      }
    }
    load();
  }, []);

  const filteredReports = reports.filter((rep) => {
    const q = searchQuery.toLowerCase().trim();
    return (
      !q ||
      rep.reportNumber.toLowerCase().includes(q) ||
      rep.commodityName.toLowerCase().includes(q) ||
      (rep.product && rep.product.toLowerCase().includes(q)) ||
      rep.inspectionId.toLowerCase().includes(q) ||
      (rep.inspectionNumber && rep.inspectionNumber.toLowerCase().includes(q)) ||
      rep.manufacturerOrPacker.toLowerCase().includes(q) ||
      (rep.company && rep.company.toLowerCase().includes(q))
    );
  });

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Statutory Verification Reports"
        description="Tamper-proof, programmatically generated Legal Metrology compliance reports with cryptographic verification hash."
      />

      {/* Filter / Search Bar */}
      <div className="flex items-center justify-between gap-3 p-4 rounded-xl border border-[#E2E8F0] bg-white shadow-2xs">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 size-3.5 text-[#94A3B8]" />
          <Input
            placeholder="Search report ID, commodity, or company..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-8 text-xs h-8 bg-[#F8FAFC] border-[#E2E8F0] focus:bg-white focus:ring-2 focus:ring-[#2563EB]/20 focus:border-[#2563EB]"
          />
        </div>

        <span className="text-xs text-[#475569]">
          {filteredReports.length} verification records logged
        </span>
      </div>

      <div className="rounded-xl border border-[#E2E8F0] bg-white p-5 shadow-2xs">
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow className="border-[#E2E8F0] bg-[#F8FAFC]">
                <TableHead className="text-[11px] font-semibold text-[#475569]">REPORT NUMBER</TableHead>
                <TableHead className="text-[11px] font-semibold text-[#475569]">INSPECTION NUMBER</TableHead>
                <TableHead className="text-[11px] font-semibold text-[#475569]">COMPANY</TableHead>
                <TableHead className="text-[11px] font-semibold text-[#475569]">PRODUCT</TableHead>
                <TableHead className="text-[11px] font-semibold text-[#475569]">DATE</TableHead>
                <TableHead className="text-[11px] font-semibold text-[#475569]">RESULT</TableHead>
                <TableHead className="text-[11px] font-semibold text-[#475569]">GENERATED BY</TableHead>
                <TableHead className="text-[11px] font-semibold text-[#475569] text-right">ACTION</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoading ? (
                <TableRow>
                  <TableCell colSpan={8} className="h-32 text-center text-xs text-[#475569]">
                    Loading verification reports...
                  </TableCell>
                </TableRow>
              ) : filteredReports.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={8} className="h-32 text-center text-xs text-[#475569]">
                    No verification reports found matching &quot;{searchQuery}&quot;.
                  </TableCell>
                </TableRow>
              ) : (
                filteredReports.map((report) => (
                  <TableRow
                    key={report.reportId}
                    onClick={() => router.push(`/reports/${report.reportId}`)}
                    className="hover:bg-[#F1F5F9]/60 cursor-pointer transition-colors border-[#E2E8F0]"
                  >
                    <TableCell className="font-mono text-xs font-semibold text-[#0F172A]">
                      {report.reportNumber}
                    </TableCell>
                    <TableCell className="font-mono text-xs text-[#475569]">
                      {report.inspectionNumber || report.inspectionId}
                    </TableCell>
                    <TableCell className="text-xs text-[#475569] max-w-37.5 truncate">
                      {report.company || report.manufacturerOrPacker}
                    </TableCell>
                    <TableCell>
                      <div className="flex flex-col">
                        <span className="text-xs font-semibold text-[#0F172A]">{report.product || report.commodityName}</span>
                        <span className="text-[11px] text-[#475569]">{report.brandName || "—"}</span>
                      </div>
                    </TableCell>
                    <TableCell className="text-xs text-[#475569] whitespace-nowrap">
                      {new Date(report.generatedAt).toLocaleDateString("en-IN", {
                        day: "2-digit",
                        month: "short",
                        year: "numeric",
                      })}
                    </TableCell>
                    <TableCell>
                      <Badge variant={report.overallResult === "PASS" ? "pass" : "fail"}>
                        {report.overallResult}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-xs text-[#475569]">
                      {report.signoff?.officerName || report.generatedBy}
                    </TableCell>
                    <TableCell className="text-right" onClick={(e) => e.stopPropagation()}>
                      <Link href={`/reports/${report.reportId}`}>
                        <Button variant="secondary" size="sm" leftIcon={<Eye className="size-3.5" />}>
                          View Document
                        </Button>
                      </Link>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  );
}
